name: Primera-env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - primer3
  - ucsc-ispcr
  - bedtools
  - blat
  - mummer
  - pip:
      - pandas
      - biopython
